on:
  push:
    branches:
      - main
      - pipelines  
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Secret Scan using Docker
      run: 
        docker run --rm -it -v "$PWD:/pwd" trufflesecurity/trufflehog:latest github --repo https://github.com/xTrAcKx/test-mutillidae.git
    - name: Secret Scanning
      uses: trufflesecurity/trufflehog@main
      with:
        extra_args: --debug 
